### ISSUE TITLE
Soundtouch

### ISSUE THREAD

**Issue by Merlinuf** [StefanSimon/homeysoundtouch#2]
Is it possible to get on/off and maybe presets? 

G8 app by the way

**Comment by StefanSimon** [comment]
Already possible since v1.0 through action cards. Looking into this for device info.

**Comment by Merlinuf** [comment]
Ok, Well i just installed your app and told the HomeKit app to show it on the home app on My iPhone and there it only shows play/pause, and skip, but not on/off


Med vänlig hälsning,

Kristoffer Persson

**Comment by Merlinuf** [comment]
@stefanSimon any update on this?

**Comment by Merlinuf** [comment]
Any update on this?


Med vänlig hälsning,

Kristoffer Persson

**Comment by StefanSimon** [comment]
Not possible to implement. Homey only supports default capabilities and presets isn't one of them.

**Comment by Merlinuf** [comment]
Well skip presets then, but ON/OFF should be possible. Now it is play/pause not really the same


Med vänlig hälsning,

Kristoffer Persson
