### ISSUE TITLE
Missing Command

### ISSUE THREAD

**Issue by jeesnl** [StefanSimon/homeysoundtouch#3]
Hi Stefan,

I'm using tour app on a Soundtouch300 sound bar and it works perfect but I'm missing the commend for playing an external Source. On the Soundtouch300 this is used for to play the sound of the TV.

Can you please add this in the near future?

Kind regards,
Jan Slag.

**Comment by StefanSimon** [comment]
Looking into this right now since I'm updating some missing features I promised a long time ago.

**Comment by StefanSimon** [comment]
Gonna need your help for this one @jeesnl . Can you do a full post of what you see when you access your soundbar IP:8090/sources ? I don't own a soundbar and the bose soundtouch api docs are ofcourse useless as &#@#$.

**Comment by phatenl** [comment]
I have a soundbar and this is what I see:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<sources deviceID="689E1952D9B5">
<sourceItem source="STORED_MUSIC" sourceAccount="c0373166-5a28-8999-a65d-3389428e5a16/0" status="UNAVAILABLE" isLocal="false" multiroomallowed="true">Plex Media Server: Desktop-Tim</sourceItem>
<sourceItem source="INTERNET_RADIO" status="READY" isLocal="false" multiroomallowed="true"/>
<sourceItem source="NOTIFICATION" status="UNAVAILABLE" isLocal="false" multiroomallowed="true"/>
<sourceItem source="QPLAY" sourceAccount="QPlay1UserName" status="UNAVAILABLE" isLocal="true" multiroomallowed="true">QPlay1UserName</sourceItem>
<sourceItem source="BLUETOOTH" status="UNAVAILABLE" isLocal="true" multiroomallowed="true"/>
<sourceItem source="QPLAY" sourceAccount="QPlay2UserName" status="UNAVAILABLE" isLocal="true" multiroomallowed="true">QPlay2UserName</sourceItem>
<sourceItem source="UPNP" sourceAccount="UPnPUserName" status="UNAVAILABLE" isLocal="false" multiroomallowed="true">UPnPUserName</sourceItem>
<sourceItem source="STORED_MUSIC_MEDIA_RENDERER" sourceAccount="StoredMusicUserName" status="UNAVAILABLE" isLocal="false" multiroomallowed="true">StoredMusicUserName</sourceItem>
<sourceItem source="ALEXA" status="READY" isLocal="false" multiroomallowed="true"/>
<sourceItem source="SPOTIFY" sourceAccount="tim-w.com" status="READY" isLocal="false" multiroomallowed="true">tim@tim-w.com</sourceItem>
<sourceItem source="SPOTIFY" status="UNAVAILABLE" isLocal="false" multiroomallowed="true"/>
<sourceItem source="TUNEIN" status="READY" isLocal="false" multiroomallowed="true"/>
</sources>

**Comment by jeesnl** [comment]
Hi Stefan,

When I start the TV I use the Source (Button 1 on picture)
Then Source on/off (Button 2 on picture)
Then the On/Off (Button 3 on the picture)

Hope it's clear with this.

For more info see attachments.

Thanks in Advance.

Jan Slag

![capture](https://user-images.githubusercontent.com/39216786/42493242-c4879edc-840b-11e8-864f-ae4d027006d5.JPG)

![source selection](https://user-images.githubusercontent.com/39216786/42492883-432ebb46-840a-11e8-8242-27ea474511dc.JPG)

**Comment by StefanSimon** [comment]
@jeesnl I think I understand what you are trying to achieve, powering on your settop box and using the soundbar remote to control the settop box. Can you confirm this?

**Comment by jeesnl** [comment]
Correct

**Comment by StefanSimon** [comment]
I'm afraid it is not possible to implement such a thing. The bose soundtouch API doesn't provide functionality to perform these actions. One of the things you could try is to learn homey the infrared signals that your remote is sending and do it that way. There is no other way possible I'm afraid.

I'm closing this issue for now.
